<?php /* =====================================================
   FILE: includes/config.php
   ===================================================== */ ?>
<?php
define('APP_NAME',  'Ramkrishna IVF Centre');
define('APP_SHORT', 'perk');
define('APP_CITY',  'Siliguri, West Bengal');

$employees = [
    ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],

    ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],

    ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],

    

];

$payroll = [
    ['name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'gross'=>62000,'pf'=>7440,'esi'=>1085,'pt'=>200,'net'=>53275,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Rajib Das',         'dept'=>'Nursing',       'gross'=>38500,'pf'=>4620,'esi'=> 673,'pt'=>150,'net'=>33057,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Sunita Paul',        'dept'=>'Reception',     'gross'=>28000,'pf'=>3360,'esi'=> 490,'pt'=>150,'net'=>24000,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Amit Roy',           'dept'=>'Lab Tech',      'gross'=>32000,'pf'=>3840,'esi'=> 560,'pt'=>150,'net'=>27450,'status'=>'pending',   'month'=>'April 2026'],
    ['name'=>'Priya Sen',          'dept'=>'Administration','gross'=>35000,'pf'=>4200,'esi'=> 612,'pt'=>150,'net'=>30038,'status'=>'pending',   'month'=>'April 2026'],
    ['name'=>'Mohan Das',          'dept'=>'Accounts',      'gross'=>42000,'pf'=>5040,'esi'=> 735,'pt'=>200,'net'=>36025,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'gross'=>62000,'pf'=>7440,'esi'=>1085,'pt'=>200,'net'=>53275,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Rajib Das',         'dept'=>'Nursing',       'gross'=>38500,'pf'=>4620,'esi'=> 673,'pt'=>150,'net'=>33057,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Sunita Paul',        'dept'=>'Reception',     'gross'=>28000,'pf'=>3360,'esi'=> 490,'pt'=>150,'net'=>24000,'status'=>'processed','month'=>'April 2026'],
];

$departments = [
    ['name'=>'Medical',       'count'=>18,'color'=>'#7C3AED'],
    ['name'=>'Nursing',       'count'=>22,'color'=>'#059669'],
    ['name'=>'Administration','count'=>10,'color'=>'#2563EB'],
    ['name'=>'Lab Tech',      'count'=> 8,'color'=>'#EA580C'],
    ['name'=>'Accounts',      'count'=> 7,'color'=>'#D97706'],
];

$attendance_today = ['present'=>49,'on_leave'=>1,'absent'=>15,'total'=>65];

$leave_requests = [
    ['name'=>'Amit Roy',   'dept'=>'Lab Tech',   'type'=>'Casual Leave',  'from'=>'2026-04-18','to'=>'2026-04-19','days'=>2,'status'=>'pending'],
    ['name'=>'Kabita Ghosh','dept'=>'Nursing',   'type'=>'Sick Leave',    'from'=>'2026-04-20','to'=>'2026-04-20','days'=>1,'status'=>'pending'],
    ['name'=>'Mohan Das',  'dept'=>'Accounts',   'type'=>'Earned Leave',  'from'=>'2026-05-01','to'=>'2026-05-03','days'=>3,'status'=>'approved'],
];

$holidays = [
    ['date'=>'2026-05-01','name'=>'May Day',          'type'=>'National'],
    ['date'=>'2026-08-15','name'=>'Independence Day',  'type'=>'National'],
    ['date'=>'2026-10-02','name'=>'Gandhi Jayanti',    'type'=>'National'],
    ['date'=>'2026-10-20','name'=>'Durga Puja',        'type'=>'Regional'],
    ['date'=>'2026-11-04','name'=>'Diwali',             'type'=>'National'],
];


/* ─────────────────────────────────────────
   MOCK DATA
───────────────────────────────────────── */
$pending_requests = [
    [
        'id'          => 1,
        'emp_name'    => 'Suman Karmakar',
        'emp_code'    => '1008',
        'stage'       => 'Stage_1',
        'type'        => 'Attendance',
        'date'        => '22 Apr 2026',
        'requested'   => '25 Apr 2026,Sat',
        'shift_date'  => '22 Apr 2026,Wed',
        'in_old'      => '11:03 AM',
        'in_new'      => '11:03 AM',
        'out_old'     => '06:38 PM',
        'out_new'     => '07:38 PM',
        'reasons'     => '',
        'remarks'     => 'Early check out due to vote',
        'avatar'      => '',
    ],
    [
        'id'          => 2,
        'emp_name'    => 'Biswajit Dutta',
        'emp_code'    => '1009',
        'stage'       => 'Stage_1',
        'type'        => 'Leave',
        'date'        => '16 Apr 2026',
        'requested'   => '16 Apr 2026,Wed',
        'shift_date'  => '16 Apr 2026,Wed',
        'in_old'      => '',
        'in_new'      => '',
        'out_old'     => '',
        'out_new'     => '',
        'reasons'     => 'Casual Leave',
        'remarks'     => 'Personal work',
        'avatar'      => '',
    ],
    [
        'id'          => 3,
        'emp_name'    => 'Supriya Mitra',
        'emp_code'    => '1100',
        'stage'       => 'Stage_1',
        'type'        => 'Attendance',
        'date'        => '16 Apr 2026',
        'requested'   => '16 Apr 2026,Wed',
        'shift_date'  => '15 Apr 2026,Tue',
        'in_old'      => '09:15 AM',
        'in_new'      => '09:00 AM',
        'out_old'     => '05:30 PM',
        'out_new'     => '06:00 PM',
        'reasons'     => '',
        'remarks'     => 'Regularisation request',
        'avatar'      => '',
    ],
    [
        'id'          => 4,
        'emp_name'    => 'Sheetal Bhutia',
        'emp_code'    => '1055',
        'stage'       => 'Stage_1',
        'type'        => 'Attendance',
        'date'        => '14 Apr 2026',
        'requested'   => '14 Apr 2026,Mon',
        'shift_date'  => '12 Apr 2026,Sat',
        'in_old'      => '10:00 AM',
        'in_new'      => '09:45 AM',
        'out_old'     => '05:00 PM',
        'out_new'     => '05:30 PM',
        'reasons'     => '',
        'remarks'     => 'Forgot to punch out',
        'avatar'      => '',
    ],
    [
        'id'          => 5,
        'emp_name'    => 'Rajib Das',
        'emp_code'    => '1012',
        'stage'       => 'Stage_1',
        'type'        => 'Attendance',
        'date'        => '12 Apr 2026',
        'requested'   => '13 Apr 2026,Sun',
        'shift_date'  => '12 Apr 2026,Sat',
        'in_old'      => '08:55 AM',
        'in_new'      => '09:00 AM',
        'out_old'     => '04:45 PM',
        'out_new'     => '05:00 PM',
        'reasons'     => '',
        'remarks'     => 'Late punch correction',
        'avatar'      => '',
    ],
    [
        'id'          => 6,
        'emp_name'    => 'Priya Sen',
        'emp_code'    => '1033',
        'stage'       => 'Stage_1',
        'type'        => 'Attendance',
        'date'        => '10 Apr 2026',
        'requested'   => '11 Apr 2026,Fri',
        'shift_date'  => '10 Apr 2026,Thu',
        'in_old'      => '09:30 AM',
        'in_new'      => '09:00 AM',
        'out_old'     => '06:00 PM',
        'out_new'     => '06:30 PM',
        'reasons'     => '',
        'remarks'     => 'System error in punch',
        'avatar'      => '',
    ],
    [
        'id'          => 7,
        'emp_name'    => 'Amit Roy',
        'emp_code'    => '1044',
        'stage'       => 'Stage_1',
        'type'        => 'Attendance',
        'date'        => '08 Apr 2026',
        'requested'   => '09 Apr 2026,Wed',
        'shift_date'  => '08 Apr 2026,Tue',
        'in_old'      => '10:05 AM',
        'in_new'      => '10:00 AM',
        'out_old'     => '06:10 PM',
        'out_new'     => '06:00 PM',
        'reasons'     => '',
        'remarks'     => 'Minor correction needed',
        'avatar'      => '',
    ],
];

function fmt_inr(int $n): string {
    return '₹' . number_format($n);
}

function initials(string $name): string {
    $parts = explode(' ', $name);
    return strtoupper(substr($parts[0],0,1) . (isset($parts[1]) ? substr($parts[1],0,1) : ''));
}

$current_page = basename($_SERVER['PHP_SELF'], '.php');
?>