
<?php /* =====================================================
   FILE: includes/config.php
   ===================================================== */ ?>
<?php
define('APP_NAME',  'Ramkrishna IVF Centre');
define('APP_SHORT', 'perk');
define('APP_CITY',  'Siliguri, West Bengal');

$employees = [
    ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],

    ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],

    ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
     ['id'=>1,'name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'role'=>'Senior Doctor',  'status'=>'active','join'=>'2021-06-01','salary'=>62000],
    ['id'=>2,'name'=>'Rajib Das',         'dept'=>'Nursing',       'role'=>'Head Nurse',     'status'=>'active','join'=>'2022-04-16','salary'=>38500],
    ['id'=>3,'name'=>'Sunita Paul',        'dept'=>'Reception',     'role'=>'Front Desk',     'status'=>'active','join'=>'2022-04-20','salary'=>28000],
    ['id'=>4,'name'=>'Amit Roy',           'dept'=>'Lab Tech',      'role'=>'Lab Technician', 'status'=>'active','join'=>'2023-01-10','salary'=>32000],
    ['id'=>5,'name'=>'Priya Sen',          'dept'=>'Administration','role'=>'Admin Executive','status'=>'active','join'=>'2023-03-15','salary'=>35000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],
    ['id'=>6,'name'=>'Mohan Das',          'dept'=>'Accounts',      'role'=>'Accountant',     'status'=>'active','join'=>'2020-09-01','salary'=>42000],
    ['id'=>7,'name'=>'Kabita Ghosh',       'dept'=>'Nursing',       'role'=>'Staff Nurse',    'status'=>'active','join'=>'2024-02-01','salary'=>30000],
    ['id'=>8,'name'=>'Suresh Mondal',      'dept'=>'Medical',       'role'=>'Junior Doctor',  'status'=>'active','join'=>'2024-07-01','salary'=>55000],

    

];

$payroll = [
    ['name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'gross'=>62000,'pf'=>7440,'esi'=>1085,'pt'=>200,'net'=>53275,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Rajib Das',         'dept'=>'Nursing',       'gross'=>38500,'pf'=>4620,'esi'=> 673,'pt'=>150,'net'=>33057,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Sunita Paul',        'dept'=>'Reception',     'gross'=>28000,'pf'=>3360,'esi'=> 490,'pt'=>150,'net'=>24000,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Amit Roy',           'dept'=>'Lab Tech',      'gross'=>32000,'pf'=>3840,'esi'=> 560,'pt'=>150,'net'=>27450,'status'=>'pending',   'month'=>'April 2026'],
    ['name'=>'Priya Sen',          'dept'=>'Administration','gross'=>35000,'pf'=>4200,'esi'=> 612,'pt'=>150,'net'=>30038,'status'=>'pending',   'month'=>'April 2026'],
    ['name'=>'Mohan Das',          'dept'=>'Accounts',      'gross'=>42000,'pf'=>5040,'esi'=> 735,'pt'=>200,'net'=>36025,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Dr. Anjali Sharma','dept'=>'Medical',       'gross'=>62000,'pf'=>7440,'esi'=>1085,'pt'=>200,'net'=>53275,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Rajib Das',         'dept'=>'Nursing',       'gross'=>38500,'pf'=>4620,'esi'=> 673,'pt'=>150,'net'=>33057,'status'=>'processed','month'=>'April 2026'],
    ['name'=>'Sunita Paul',        'dept'=>'Reception',     'gross'=>28000,'pf'=>3360,'esi'=> 490,'pt'=>150,'net'=>24000,'status'=>'processed','month'=>'April 2026'],
];

$departments = [
    ['name'=>'Medical',       'count'=>18,'color'=>'#7C3AED'],
    ['name'=>'Nursing',       'count'=>22,'color'=>'#059669'],
    ['name'=>'Administration','count'=>10,'color'=>'#2563EB'],
    ['name'=>'Lab Tech',      'count'=> 8,'color'=>'#EA580C'],
    ['name'=>'Accounts',      'count'=> 7,'color'=>'#D97706'],
];

$attendance_today = ['present'=>49,'on_leave'=>1,'absent'=>15,'total'=>65];

$leave_requests = [
    ['name'=>'Amit Roy',   'dept'=>'Lab Tech',   'type'=>'Casual Leave',  'from'=>'2026-04-18','to'=>'2026-04-19','days'=>2,'status'=>'pending'],
    ['name'=>'Kabita Ghosh','dept'=>'Nursing',   'type'=>'Sick Leave',    'from'=>'2026-04-20','to'=>'2026-04-20','days'=>1,'status'=>'pending'],
    ['name'=>'Mohan Das',  'dept'=>'Accounts',   'type'=>'Earned Leave',  'from'=>'2026-05-01','to'=>'2026-05-03','days'=>3,'status'=>'approved'],
];

$holidays = [
    ['date'=>'2026-05-01','name'=>'May Day',          'type'=>'National'],
    ['date'=>'2026-08-15','name'=>'Independence Day',  'type'=>'National'],
    ['date'=>'2026-10-02','name'=>'Gandhi Jayanti',    'type'=>'National'],
    ['date'=>'2026-10-20','name'=>'Durga Puja',        'type'=>'Regional'],
    ['date'=>'2026-11-04','name'=>'Diwali',             'type'=>'National'],
];

$approvals = [
    ['type'=>'Leave',           'icon'=>'📅','employee'=>'Amit Roy',    'detail'=>'Casual Leave · 2 days'],
    ['type'=>'Overtime',        'icon'=>'⏰','employee'=>'Priya Sen',   'detail'=>'4 hrs overtime'],
    ['type'=>'Salary Revision', 'icon'=>'💰','employee'=>'Mohan Das',   'detail'=>'+8% increment'],
    ['type'=>'Leave',           'icon'=>'📅','employee'=>'Amit Roy',    'detail'=>'Casual Leave · 2 days'],
    ['type'=>'Overtime',        'icon'=>'⏰','employee'=>'Priya Sen',   'detail'=>'4 hrs overtime'],
    ['type'=>'Salary Revision', 'icon'=>'💰','employee'=>'Mohan Das',   'detail'=>'+8% increment'],
    ['type'=>'Leave',           'icon'=>'📅','employee'=>'Amit Roy',    'detail'=>'Casual Leave · 2 days'],
    ['type'=>'Overtime',        'icon'=>'⏰','employee'=>'Priya Sen',   'detail'=>'4 hrs overtime'],
    ['type'=>'Salary Revision', 'icon'=>'💰','employee'=>'Mohan Das',   'detail'=>'+8% increment'],
    ['type'=>'Leave',           'icon'=>'📅','employee'=>'Amit Roy',    'detail'=>'Casual Leave · 2 days'],
    ['type'=>'Overtime',        'icon'=>'⏰','employee'=>'Priya Sen',   'detail'=>'4 hrs overtime']

];

function fmt_inr(int $n): string {
    return '₹' . number_format($n);
}

function initials(string $name): string {
    $parts = explode(' ', $name);
    return strtoupper(substr($parts[0],0,1) . (isset($parts[1]) ? substr($parts[1],0,1) : ''));
}

$current_page = basename($_SERVER['PHP_SELF'], '.php');
?>
